(() => {
  const roles = {viewer:'只读用户',engineer:'工艺工程师',process_manager:'工艺技术经理',reviewer:'校核人员（历史角色）',process_director:'工艺技术总监',admin:'系统管理员'};
  let me = null;
  const token = () => localStorage.getItem('authToken') || localStorage.getItem('cad_engine_token') || '';
  const api = async (url, options = {}) => { const response = await fetch(url, {...options,headers:{...(options.body && !(options.body instanceof FormData) ? {'Content-Type':'application/json'} : {}),Authorization:`Bearer ${token()}`,...(options.headers || {})}}); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || '请求失败'); return data; };
  const message = (text, ok = false) => { const el = document.querySelector('#accountMessage'); el.textContent = text; el.classList.toggle('ok', ok); };
  const options = (selected, includeAdmin = false) => Object.entries(roles).filter(([key]) => includeAdmin || key !== 'admin').map(([key,label]) => `<option value="${key}" ${key===selected?'selected':''}>${label}</option>`).join('');
  async function loadUsers() { const data = await api('/api/users'); document.querySelector('#userRows').innerHTML = (data.users || []).map(user => `<tr><td><strong>${esc(user.display_name)}</strong><br><small>${esc(user.username)}</small></td><td><span class="account-role">${esc(roles[user.role] || user.role)}</span></td><td>${esc(roles[user.requested_role] || user.requested_role || '—')}</td><td>${user.is_system?'<span>历史归档</span>':user.role==='admin'?'<span>管理员</span>':`<select data-role-user="${esc(user.username)}">${options(user.role)}</select>`}</td><td>${user.is_system||user.role==='admin'?'':`<button class="account-save-role" data-save-user="${esc(user.username)}">保存</button>`}</td></tr>`).join(''); document.querySelectorAll('[data-save-user]').forEach(button => button.onclick = async () => { const username = button.dataset.saveUser; const role = document.querySelector(`[data-role-user="${CSS.escape(username)}"]`).value; button.disabled = true; try { await api(`/api/users/${encodeURIComponent(username)}/role`, {method:'PUT',body:JSON.stringify({role})}); await loadUsers(); } catch (error) { message(error.message); button.disabled = false; } }); }
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  async function start() { if (!token()) { location.href = 'auth.html?next=account.html'; return; } try { const data = await api('/api/me'); me = data.user; document.querySelector('#displayName').value = me.display_name || ''; document.querySelector('#accountSummary').textContent = `${me.username} · ${roles[me.role] || me.role}`; if (me.role === 'admin') { document.querySelector('#userAdmin').hidden = false; await loadUsers(); } } catch { localStorage.removeItem('authToken'); localStorage.removeItem('cad_engine_token'); location.href = 'auth.html?next=account.html'; } }
  document.querySelector('#profileForm').onsubmit = async event => { event.preventDefault(); const button = event.submitter; button.disabled = true; message(''); try { const data = await api('/api/me', {method:'PUT',body:JSON.stringify({display_name:document.querySelector('#displayName').value.trim(),current_password:document.querySelector('#currentPassword').value,new_password:document.querySelector('#newPassword').value})}); localStorage.setItem('authToken', data.token); localStorage.setItem('cad_engine_token', data.token); me = data.user; document.querySelector('#currentPassword').value = ''; document.querySelector('#newPassword').value = ''; document.querySelector('#accountSummary').textContent = `${me.username} · ${roles[me.role] || me.role}`; message('资料已保存。', true); } catch (error) { message(error.message); } finally { button.disabled = false; } };
  document.querySelector('#logoutBtn').onclick = () => { localStorage.removeItem('authToken'); localStorage.removeItem('cad_engine_token'); location.href = 'auth.html'; };
  document.querySelector('#reloadUsers').onclick = () => loadUsers().catch(error => message(error.message));
  start();
})();
