/* 首页需求单详情：参考稿的时间线信息架构，状态和入口全部读取项目真实流程数据。 */
const rdPid=new URLSearchParams(location.search).get('project')||localStorage.getItem('cad_engine_project_id')||'';
const rdEsc=value=>esc(value??'');
const rdCheck='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><polyline points="20 6 9 17 4 12"></polyline></svg>';
const rdWait='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>';
function rdHas(value){if(Array.isArray(value))return value.some(rdHas);if(value&&typeof value==='object')return Object.entries(value).some(([key,item])=>!['project_id','updated_at','timing','confirmed','confirmed_by','confirmed_at'].includes(key)&&rdHas(item));return typeof value==='string'?Boolean(value.trim()):value!==null&&value!==undefined&&value!==false;}
function rdDate(value){return value?String(value).replace('T',' ').slice(0,16):'—';}
function rdLink(path){return path.startsWith('/')?path:`${path}${path.includes('?')?'&':'?'}project=${encodeURIComponent(rdPid)}`;}
function rdEvent(history,needle){return (history||[]).slice().reverse().find(item=>String(item.action||'').includes(needle));}
function rdState(done,active=false,returned=false){if(returned)return {key:'returned',label:'已退回',icon:rdWait};if(done)return {key:'completed',label:'已完成',icon:rdCheck};if(active)return {key:'active',label:'处理中',icon:rdWait};return {key:'pending',label:'等待中',icon:rdWait};}
function rdStep(code,title,state,owner,date,conclusion,detail,link){return {code,title,state,owner:owner||'—',date:rdDate(date),conclusion:conclusion||'等待中',detail,link};}
function rdRenderStep(item){return `<article class="detail-timeline-item" data-timeline-item><div class="detail-timeline-node ${item.state.key}">${item.state.icon}</div><div class="detail-timeline-card${item.state.key==='active'?' active':''}"><div class="detail-timeline-header"><div class="detail-timeline-title"><span class="timeline-code">${rdEsc(item.code)}</span>${rdEsc(item.title)}</div><span class="detail-timeline-status ${item.state.key}">${rdEsc(item.state.label)}</span></div><div class="detail-timeline-meta"><div class="detail-meta-item"><span class="detail-meta-label">接口人</span><span class="detail-meta-value">${rdEsc(item.owner)}</span></div><div class="detail-meta-item"><span class="detail-meta-label">完成日期</span><span class="detail-meta-value">${rdEsc(item.date)}</span></div><div class="detail-meta-item"><span class="detail-meta-label">评估结论</span><span class="detail-meta-value">${rdEsc(item.conclusion)}</span></div></div><div class="detail-timeline-detail"><p class="detail-detail-text">${rdEsc(item.detail)}</p>${item.link?`<a class="detail-step-link" href="${rdEsc(item.link)}" onclick="event.stopPropagation()">进入此步骤 →</a>`:''}</div></div></article>`;}
function rdTechLink(index){return `/apps/tech-process/?biz=tech&project=${encodeURIComponent(rdPid)}&step=${index}`;}
function rdBuildSteps(flow,project,requirement,report,ir,aggregate){const req=requirement||{},data=req.data||{},history=req.history||[],audit=flow.audit||[],steps=aggregate?.steps||{};const created=Boolean(req.project_id),confirmed=Boolean(req.confirmed_at)||['pending_review','approved'].includes(req.status),reviewed=req.status==='approved',returned=req.status==='rejected';const parsed=Boolean(ir?.parts?.length||project?.has_ir||project?.stages?.parsed);const material=rdHas(steps.material||{}),manufacturing=rdHas(steps.manufacturing||{}),cleaning=rdHas(steps.cleaning||{}),assembly=rdHas(steps.assembly||{}),production=rdHas(steps.production||{});const prepared=Boolean(report?.prepared_at||report?.report_no),reportReviewed=['approved','published'].includes(report?.status),published=report?.status==='published';const creator=req.created_by||project.owner||'系统';const confirmEvent=rdEvent(history,'requirement_confirm')||rdEvent(history,'requirement_submitted');const reviewEvent=rdEvent(history,'requirement_review');const parsedAudit=audit.slice().reverse().find(x=>String(x.action||'').includes('parse'));const processOwner='工艺工程师';return [
rdStep('1.1','需求创建',rdState(created,!created),creator,req.created_at,created?'完成需求收集，已提交需求单':'等待创建需求单',created?'需求基本信息、技术要求和图纸资料均保存在本项目中，可随时进入表单继续补充。':'请先创建并保存工艺评估需求单。',rdLink('requirement-create.html')),
rdStep('1.2','需求确认',rdState(confirmed,created&&!confirmed),req.confirmed_by||confirmEvent?.actor||'需求接口人',req.confirmed_at||confirmEvent?.at,confirmed?'需求完整准确，已确认':'等待确认','对需求字段、图纸与技术资料进行完整性确认；确认意见会写入流程留痕。',rdLink('requirement-confirm.html')),
rdStep('1.3','需求审核',rdState(reviewed,confirmed&&!reviewed,returned),req.reviewed_by||reviewEvent?.actor||'工艺技术经理',req.reviewed_at||reviewEvent?.at,returned?'审核退回修改':reviewed?'审核通过，进入图纸解析':'等待审核','工艺技术经理进行最终审核；审核通过后项目进入图纸解析与技术工艺流程。',rdLink('requirement-review.html')),
rdStep('2.1','图纸解析',rdState(parsed,reviewed&&!parsed),parsedAudit?.detail?.by||processOwner,project.stages?.parsed||parsedAudit?.ts,parsed?'图纸解析完成':'等待图纸解析','解析上传的 2D 图纸和模型资料，提取零件、尺寸、材料与关键技术要求。',rdLink('index.html')),
rdStep('3.1','汇总结果',rdState(prepared,parsed&&!prepared),report?.prepared_by||'工艺技术经理',report?.prepared_at,prepared?'工艺评估报告已汇总':'等待汇总','汇总图纸解析与各项技术工艺结果，形成可编辑的工艺评估报告。',rdLink('summary.html')),
rdStep('3.2','审核报告',rdState(reportReviewed,prepared&&!reportReviewed,report?.status==='rejected'),report?.reviewed_by||'工艺技术总监',report?.reviewed_at,report?.status==='rejected'?'报告退回修改':reportReviewed?'报告审核通过':'等待报告审核','审核工艺评估报告的完整性、可行性结论与分发范围。',rdLink('report-review.html')),
rdStep('3.3','发布报告',rdState(published,reportReviewed&&!published),report?.published_by||'工艺技术总监',report?.published_at,published?'报告已正式发布':'等待正式发布','将审核通过的工艺评估报告正式发布，并记录分发对象、时间和版本。',rdLink('report-publish.html'))
];}
async function rdStart(){if(!rdPid){location.href='home.html';return;}try{const [flow,projectResult,aggregateResult]=await Promise.all([api(`/api/projects/${encodeURIComponent(rdPid)}/workflow`),api(`/api/projects/${encodeURIComponent(rdPid)}`),api(`/api/projects/${encodeURIComponent(rdPid)}/summary`).catch(()=>({steps:{}}))]);const project=flow.project||projectResult.meta||{},requirement=flow.requirement||null,report=flow.report||null,ir=projectResult.ir||{};const data=requirement?.data||{};const steps=rdBuildSteps(flow,project,requirement,report,ir,aggregateResult);document.querySelector('#app').innerHTML=`<button class="detail-back-button" type="button" id="rdBack"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>返回</button><h1 class="detail-page-title">江丰半导体工艺评估需求单流程展示</h1><section class="detail-header-bar"><div class="detail-header-item"><span class="detail-header-label">需求单号：</span><span class="detail-header-value">${rdEsc(requirement?.requirement_no||`PRJ-${rdPid}`)}</span></div><div class="detail-header-item"><span class="detail-header-label">客户名称：</span><span class="detail-header-value">${rdEsc(data.final_customer_name||data.customer_project||'—')}</span></div><div class="detail-header-item"><span class="detail-header-label">提交人：</span><span class="detail-header-value">${rdEsc(requirement?.created_by||project.owner||'系统')}</span></div><div class="detail-header-item"><span class="detail-header-label">提交日期：</span><span class="detail-header-value">${rdEsc(rdDate(requirement?.created_at||project.created_at).slice(0,10))}</span></div></section><section class="detail-main-content"><div class="process-timeline">${steps.map(rdRenderStep).join('')}</div></section>`;document.querySelector('#rdBack').onclick=()=>{if(history.length>1)history.back();else location.href='home.html';};document.querySelectorAll('[data-timeline-item]').forEach(item=>item.onclick=()=>item.classList.toggle('expanded'));}catch(error){document.querySelector('#app').innerHTML=`<div class="detail-error">加载需求详情失败：${rdEsc(error.message)}</div>`;}}
rdStart();
