#!/usr/bin/env python3
"""将新版 DA 的明确增量同步到报价 Postgres 主数据 schema。

默认只读对账；``--apply`` 才执行一次事务内的幂等加表/加列/演示字典种子。
不覆盖既有行、不回填猜测值、不创建价格或审核通过的主数据。
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import cpq_db  # noqa: E402
import cpq_industries  # noqa: E402
from tech_app.backend.services import industry_templates  # noqa: E402

NEW_TABLES = ("industry", "para_catalog", "industry_para")
ADDITIONAL_COLUMNS = {
    "product_para_value": {
        "para_code": "varchar(128)",
        "para_name": "text",
        "para_value": "text",
    },
    "md_clm_material_category": {"industry_code": "varchar(64)"},
    "md_clm_process_routing_base_info": {"product_item_code": "varchar(128)"},
}
SOURCE = "mock_from_industry_template"
REVIEW = "draft"


def seed_rows() -> tuple[list[tuple], list[tuple], list[tuple]]:
    """只用现有四行业注册表和前端已使用的需求字段模板生成演示字典。"""
    industries = [(key, cpq_industries.INDUSTRIES[key]["label"])
                  for key in cpq_industries.INDUSTRY_KEYS]
    catalog: dict[str, str] = {}
    links: list[tuple] = []
    for industry, blocks in industry_templates.SPECS.items():
        for block in blocks:
            for field in block.fields:
                prior = catalog.setdefault(field.key, field.label)
                if prior != field.label:
                    raise ValueError(f"同一参数编码有不同名称：{field.key}: {prior} / {field.label}")
                links.append((industry, field.key, ""))
    if {row[0] for row in industries} != set(industry_templates.SPECS):
        raise ValueError("行业注册表与需求字段模板不一致")
    return industries, list(catalog.items()), links


def validate_da() -> None:
    """迁移白名单必须全部存在于 Excel 的待接入定义，防止代码与 DA 分叉。"""
    pending = {e["table"]: {a["code"] for a in e["attrs"]}
               for e in cpq_db._load_ontology_xlsx()["pending"]["entities"]}
    for table in NEW_TABLES:
        if table not in pending:
            raise ValueError(f"DA 未定义新表：{table}")
    for table, columns in ADDITIONAL_COLUMNS.items():
        if not set(columns) <= pending.get(table, set()):
            raise ValueError(f"DA 未定义待补列：{table} / {sorted(columns)}")


def inspect(conn) -> dict[str, set[str]]:
    names = [*NEW_TABLES, *ADDITIONAL_COLUMNS]
    with conn.cursor() as cur:
        cur.execute(
            "SELECT table_name, column_name FROM information_schema.columns "
            "WHERE table_schema=%s AND table_name=ANY(%s)",
            (cpq_db.PG_SCHEMA, names),
        )
        columns: dict[str, set[str]] = {}
        for table, column in cur.fetchall():
            columns.setdefault(table, set()).add(column)
    return columns


def plan(columns: dict[str, set[str]]) -> dict:
    industries, catalog, links = seed_rows()
    return {
        "new_tables": [t for t in NEW_TABLES if not columns.get(t)],
        "new_columns": {t: sorted(set(extra) - columns.get(t, set()))
                        for t, extra in ADDITIONAL_COLUMNS.items()
                        if set(extra) - columns.get(t, set())},
        "seed_rows": {"industry": len(industries), "para_catalog": len(catalog),
                      "industry_para": len(links)},
    }


def apply(conn) -> None:
    from psycopg import sql

    table = lambda name: sql.Identifier(cpq_db.PG_SCHEMA, name)
    industries, catalog, links = seed_rows()
    present = inspect(conn)
    with conn.cursor() as cur:
        cur.execute("SET LOCAL lock_timeout = '3s'")
        if "industry" not in present:
            cur.execute(sql.SQL("""CREATE TABLE IF NOT EXISTS {} (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            industry_code varchar(64) NOT NULL UNIQUE,
            industry_name varchar(128) NOT NULL,
            data_source text NOT NULL DEFAULT 'mock_from_industry_template',
            review_status text NOT NULL DEFAULT 'draft'
        )""").format(table("industry")))
        if "para_catalog" not in present:
            cur.execute(sql.SQL("""CREATE TABLE IF NOT EXISTS {} (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            para_code varchar(128) NOT NULL UNIQUE,
            para_name text NOT NULL,
            para_type varchar(64),
            data_source text NOT NULL DEFAULT 'mock_from_industry_template',
            review_status text NOT NULL DEFAULT 'draft'
        )""").format(table("para_catalog")))
        if "industry_para" not in present:
            cur.execute(sql.SQL("""CREATE TABLE IF NOT EXISTS {} (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            industry_code varchar(64) NOT NULL REFERENCES {}(industry_code),
            para_code varchar(128) NOT NULL REFERENCES {}(para_code),
            product_catagory_code varchar(128) NOT NULL DEFAULT '',
            data_source text NOT NULL DEFAULT 'mock_from_industry_template',
            review_status text NOT NULL DEFAULT 'draft',
            UNIQUE (industry_code, para_code, product_catagory_code)
        )""").format(table("industry_para"), table("industry"), table("para_catalog")))
        for name, extra in ADDITIONAL_COLUMNS.items():
            for col, data_type in extra.items():
                if col in present.get(name, set()):
                    continue
                cur.execute(sql.SQL("ALTER TABLE {} ADD COLUMN IF NOT EXISTS {} {}").format(
                    table(name), sql.Identifier(col), sql.SQL(data_type)))
        cur.executemany(sql.SQL(
            "INSERT INTO {} (industry_code, industry_name, data_source, review_status) "
            "VALUES (%s, %s, %s, %s) ON CONFLICT (industry_code) DO NOTHING"
        ).format(table("industry")), [(key, label, SOURCE, REVIEW) for key, label in industries])
        cur.executemany(sql.SQL(
            "INSERT INTO {} (para_code, para_name, data_source, review_status) "
            "VALUES (%s, %s, %s, %s) ON CONFLICT (para_code) DO NOTHING"
        ).format(table("para_catalog")), [(code, label, SOURCE, REVIEW) for code, label in catalog])
        cur.executemany(sql.SQL(
            "INSERT INTO {} (industry_code, para_code, product_catagory_code, data_source, review_status) "
            "VALUES (%s, %s, %s, %s, %s) "
            "ON CONFLICT (industry_code, para_code, product_catagory_code) DO NOTHING"
        ).format(table("industry_para")), [(*row, SOURCE, REVIEW) for row in links])


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="提交幂等加表、加列和未审核演示字典")
    args = parser.parse_args(argv)
    validate_da()
    conn = cpq_db.connect(readonly=not args.apply, autocommit=False)
    try:
        before = plan(inspect(conn))
        print("迁移前：", before)
        if not args.apply:
            conn.rollback()
            return 0
        apply(conn)
        after = plan(inspect(conn))
        if after["new_tables"] or after["new_columns"]:
            raise RuntimeError(f"迁移后仍缺少表或字段：{after}")
        conn.commit()
        print("已提交；迁移后：", after)
        return 0
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
